### ISSUE TITLE
Liquid Exception: Liquid syntax error (line 1): 'endfor' is not a valid delimiter for if tags. use endif in /srv/jekyll/_layouts/compress.html

### ISSUE THREAD

**Issue by NanoCode012** [penibelst/jekyll-compress-html#103]
Hello,

I'm not sure if this repo is still maintained but I got this error with the latest Jekyll.

```
Liquid Exception: Liquid syntax error (line 1): 'endfor' is not a valid delimiter for if tags. use endif in /srv/jekyll/_layouts/compress.html
```

I did as the documentation said:
1. Add `compress.html` to `_layouts` folder
1. Add it to one of my `layouts`.

I used a docker image of Jekyll for this. I tried to replace the `endfor` to `endif` one by one but it didn't work.

Here is the full error log:

```
Liquid Exception: Liquid syntax error (line 1): 'endfor' is not a valid delimiter for if tags. use endif in /srv/jekyll/_layouts/compress.html

------------------------------------------------

Jekyll 4.2.0 Please append `--trace` to the `serve` command

for any additional information or backtrace.

------------------------------------------------

/usr/gem/gems/liquid-4.0.3/lib/liquid/block.rb:33:in `unknown_tag': Liquid syntax error (line 1): 'endfor' is not a valid delimiter for if tags. use endif (Liquid::SyntaxError)

from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:38:in `unknown_tag'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/block.rb:68:in `block in parse_body'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:32:in `parse'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/block.rb:58:in `parse_body'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:30:in `parse'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/tag.rb:10:in `parse'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:34:in `parse'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'

from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:116:in `parse'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:12:in `parse'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:126:in `render_liquid'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:194:in `render_layout'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:163:in `place_in_layouts'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:93:in `render_document'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:63:in `run'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:547:in `render_regenerated'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:539:in `block in render_pages'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `each'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `render_pages'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:211:in `render'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'

from /usr/gem/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'

from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'

from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'

from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'

from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'

from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'

from /usr/gem/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'

from /usr/local/bundle/bin/jekyll:29:in `load'

from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

Thank you for reading.

**Comment by jnvsor** [comment]
I haven't worked with jekyll in a long time, but this project has essentially been "Complete" for a few years.

It looks like liquid 4 just came out and made some syntax changes. Can you use the uncompressed compressor (Stupid, I know) to find the actual line the error is on?

Stick the yaml and liquid files [here](https://github.com/penibelst/jekyll-compress-html/tree/master/src) together to make a compress layout, that'll point out which line of the code is actually causing the issue.
